name: Docker Image CI

on:
  release:
    types: published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login \
          -u ${{ vars.DOCKER_HUB_USER }} \
          -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . --file Dockerfile --tag fakeapate/pz-server-manager:${{ github.event.release.tag_name }}
        docker push fakeapate/pz-server-manager:${{ github.event.release.tag_name }}
