name: Deploy with Remote Docker

on:
  release:
    types: published

jobs:
  deploy:
    uses: RedNoodlesOrg/rednet-actions-workflows/.github/workflows/docker-build-push.yml@main
    secrets: inherit